name: Push git subdirectory as branch

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pkg
          FOLDER: pkg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
